import React, { useContext } from 'react'
import { assets } from '../assets/assets'
import {delay, motion} from 'motion/react'
import { AppContext } from '../context/AppContext'
import { Navigate ,useNavigate} from 'react-router-dom'

const Header = () => {
    const navigate=useNavigate();
    const {user,setShowLogin}=useContext(AppContext);
    const ClickHandler=()=>{
        if(user){
            navigate("/result");
        }
        else{
            setShowLogin(true);
        }
    }
  return (
    <motion.div className='flex flex-col items-center justify-between py-10 '
     initial={{opacity:0.2,y:100}}
     transition={{duration:1}}
     whileInView={{opacity:1,y:0}}
     viewport={{once:true}}
    >



        <motion.div className='inline-flex items-center gap-2 text-center text-slate-500 border border-neutral-500 rounded-full px-2 py-2'
         initial={{opacity:0,y:-20}}
        animate={{opacity:1,y:0}}
         transition={{delay:0.2,duration:0.8}}
     viewport={{once:true}}>
            <p>Best text to image generator</p>
            <img src={assets.star_icon} alt="" />
        </motion.div>
        <motion.h1 initial={{opacity:0}} animate={{opacity:1}} transition={{delay:0.5,duration:0.8}} className='text-4xl max-w-[300px] sm:text-7xl sm:max-w-[590px] text-center m-auto mt-10'
        
        >Turn text to 
            <span className='text-blue-600'> image</span> in seconds.</motion.h1>
            <motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:0.8,duration:0.8}} className='text-center max-w-xl m-auto mt-5'>
                Unleash Your creativity with AI . Convert your imagination in visual art in seconds - just type, and watch the magic happen
            </motion.p>
            <motion.button onClick={ClickHandler} className='cursor-pointer bg-black rounded-full m-auto mt-5 py-4 px-8 text-white flex items-center gap-2 '
            whileTap={{scale:0.8}}>Generate Image 
                <motion.img whileHover={{scale:1.2,duration:1}} className='w-5 hover:translate-y-3 transition-all duration-500' src={assets.star_group} alt="" />
            </motion.button>
            <div className='mt-5 flex items-center gap-2'>
                {Array(6).fill('').map((item,idx)=>(
                    <img className='hover:scale-105 transition-all duration-300 cursor-pointer rounded' src={idx%2===0?assets.sample_img_2:assets.sample_img_1} key={idx} width={70} alt="" />
))}
            </div>
            <p className='text-sm m-auto mt-3 text-slate-400'>Images generated by Imagify</p>
    </motion.div>
  )
}

export default Header